[package]
name = "aquic"
version = "0.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt", "net", "sync"] }
tokio-util = "0.7.17"
quiche = "0.24.6"

tracing = "0.1.43"
futures = "0.3.31"
bytes = "1.11.0"
